---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-dep
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: tom-app
 template:
  metadata:
   labels:
     app: tom-app	 
  spec: 
    containers:
    - name: tom-cont
      image: rajeshkancherla91/tom-img
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: svc-dep
spec:
  type: NodePort
  selector:
   app: tom-app
  ports:
   - port: 1234
     targetPort: 8080
...
